name: Go

on:
  push:

env:
  GO_VERSION: "1.21"

jobs:
  build-x86:
    runs-on: macos-11

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go ${{ env.GO_VERSION }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true

      - name: Build
        run: go build -v -ldflags "-X main.Commit=${{ github.sha }}"

      - name: Run the binary
        run: ./mac-registration-provider -once

      - uses: actions/upload-artifact@v3
        with:
          name: mac-registration-provider-x86
          path: mac-registration-provider
          if-no-files-found: error
